/*
 * LoginFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.itshixun.view;

import java.io.UnsupportedEncodingException;

import com.itshixun.model.User;
import com.itshixun.service.UserService;
import com.itshixun.service.UserTypeService;
import com.itshixun.service.impl.UserServiceImpl;
import com.itshixun.service.impl.UserTypeServiceImpl;

/**
 * 
 * @author __USER__
 */
public class LoginFrame extends javax.swing.JFrame {
	UserTypeService userTypeService = new UserTypeServiceImpl();
	UserService userService = new UserServiceImpl();

	/** Creates new form LoginFrame */
	public LoginFrame() {
		initComponents();
		this.setLocationRelativeTo(null);
		userTypeService.showUserType(limit);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		loginTitle = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		uname = new javax.swing.JTextField();
		pwd = new javax.swing.JPasswordField();
		limit = new javax.swing.JComboBox();
		jLabel3 = new javax.swing.JLabel();
		loginBtn = new javax.swing.JButton();
		registerBtn = new javax.swing.JButton();
		mess_name = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setForeground(java.awt.Color.white);
		setResizable(false);
		setState(1);

		loginTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 44));
		loginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		loginTitle
				.setText("\u4eba\u529b\u8d44\u6e90\u7cfb\u7edf\u2014\u2014\u767b\u5f55\u754c\u9762");

		jLabel1.setText("\u7528\u6237\u540d\uff1a");

		jLabel2.setText("\u5bc6   \u7801\uff1a");

		uname.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				unameActionPerformed(evt);
			}
		});
		uname.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				unameFocusGained(evt);
			}
		});

		jLabel3.setText("\u6743   \u9650\uff1a");

		loginBtn.setText("\u767b\u9646");
		loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				try {
					loginBtnMouseClicked(evt);
				} catch (UnsupportedEncodingException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		registerBtn.setText("\u6ce8\u518c");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(
																												209,
																												209,
																												209)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel2)
																														.addComponent(
																																jLabel3)
																														.addComponent(
																																jLabel1))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																limit,
																																0,
																																182,
																																Short.MAX_VALUE)
																														.addComponent(
																																pwd,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																182,
																																Short.MAX_VALUE)
																														.addComponent(
																																uname,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																182,
																																Short.MAX_VALUE))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jPanel1Layout
																										.createSequentialGroup()
																										.addContainerGap()
																										.addComponent(
																												loginBtn)
																										.addGap(
																												78,
																												78,
																												78)
																										.addComponent(
																												registerBtn)
																										.addGap(
																												28,
																												28,
																												28)))
																		.addComponent(
																				mess_name,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				179,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				106,
																				106,
																				106)
																		.addComponent(
																				loginTitle)))
										.addGap(139, 139, 139)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(118, 118, 118)
										.addComponent(loginTitle)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				87,
																				87,
																				87)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel1)
																						.addComponent(
																								uname,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				27,
																				27,
																				27)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								pwd,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				35,
																				35,
																				35)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel3)
																						.addComponent(
																								limit,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				56,
																				56,
																				56)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								loginBtn)
																						.addComponent(
																								registerBtn)))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				84,
																				84,
																				84)
																		.addComponent(
																				mess_name,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				27,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(107, 107, 107)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addComponent(
						jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 602,
						Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents
	private void unameActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void unameFocusGained(java.awt.event.FocusEvent evt) {
		this.mess_name.setText("友情提醒：至少2位英文名称");
	}

	private void loginBtnMouseClicked(java.awt.event.MouseEvent evt)
			throws UnsupportedEncodingException {
		String name = this.uname.getText();
		String pwd = this.pwd.getText();
		String limit = this.limit.getSelectedItem().toString();
		if ("".equals(name)) {

			this.mess_name.setText("姓名为空，请重新输入！");

			return;
		}
		int type = 0;
		if ("管理员".equals(limit)) {
			type = 1;
		} else if ("普通员工".equals(limit)) {
			type = 2;
		}
		User user = new User(name, pwd, type);
		User flag = userService.login(user);
		if (flag.getTypeNo() == 1) {
			MainFrame main = new MainFrame();
			this.setVisible(false);
			main.setVisible(true);
			main.login = this;
			String mess = "欢迎" + flag.getUserName() + "登录";
			main.getjMenu4().setText(mess);
		} else if (flag.getTypeNo() == 2) {
			MainFrame2 main2 = new MainFrame2();
			this.setVisible(false);
			main2.setVisible(true);
			main2.login = this;
			String mess = "欢迎" + flag.getUserName() + "登录";
			main2.getjMenu4().setText(mess);
		}else{
			this.mess_name.setText("用户名或密码或权限错误");
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {

				LoginFrame login = new LoginFrame();
				/*
				 * login.getGraphicsConfiguration().getDevice()
				 * .setFullScreenWindow(login);
				 */
				login.setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JComboBox limit;
	private javax.swing.JButton loginBtn;
	private javax.swing.JLabel loginTitle;
	private javax.swing.JLabel mess_name;
	private javax.swing.JPasswordField pwd;
	private javax.swing.JButton registerBtn;
	private javax.swing.JTextField uname;
	// End of variables declaration//GEN-END:variables

}