/*
 * t_sal_change.java
 *
 * Created on __DATE__, __TIME__
 */

package com.itshixun.view;

import java.text.SimpleDateFormat;

import com.itshixun.model.StaffSal;
import com.itshixun.service.StaffSalService;
import com.itshixun.service.impl.StaffSalServiceImpl;

/**
 *
 * @author  __USER__
 */
public class SalChangeView extends javax.swing.JInternalFrame {
	StaffSalService staffSalService = new StaffSalServiceImpl();

	/** Creates new form t_sal_change */
	public SalChangeView() {

		initComponents();
		staffSalService.findAllStaffSal(jTable1);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		leftPanel = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		rightPanel = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		txRecordNo = new javax.swing.JTextField();
		txStartSal = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		txId = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		txEndSal = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		txReason = new javax.swing.JTextField();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		result = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "更改记录编号", "员工编号", "调前薪资", "调后薪资", "调薪原因" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false,
					false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton1.setText("\u6dfb\u52a0");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton2.setText("\u5220\u9664");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton4.setText("\u67e5\u8be2");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(
				leftPanel);
		leftPanel.setLayout(leftPanelLayout);
		leftPanelLayout.setHorizontalGroup(leftPanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				leftPanelLayout.createSequentialGroup().addContainerGap(35,
						Short.MAX_VALUE).addGroup(
						leftPanelLayout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jButton4).addComponent(jButton2)
								.addComponent(jButton1)).addGap(27, 27, 27)));
		leftPanelLayout
				.setVerticalGroup(leftPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								leftPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jButton1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton2).addGap(18, 18,
												18).addComponent(jButton4)
										.addContainerGap(65, Short.MAX_VALUE)));

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel3.setText("\u8c03\u524d\u85aa\u8d44");

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel1.setText("\u66f4\u6539\u8bb0\u5f55\u7f16\u53f7");

		txRecordNo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		txStartSal.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel2.setText("\u5458\u5de5\u7f16\u53f7");

		txId.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel4.setText("\u8c03\u540e\u85aa\u8d44");

		txEndSal.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel5.setText("\u8c03\u85aa\u539f\u56e0");

		txReason.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jButton5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton5.setText("\u786e\u8ba4");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton6.setText("\u786e\u8ba4");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jButton8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton8.setText("\u786e\u8ba4");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});

		result.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		result.setText("\u64cd\u4f5c\u5b8c\u6210");

		jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));

		javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(
				rightPanel);
		rightPanel.setLayout(rightPanelLayout);
		rightPanelLayout
				.setHorizontalGroup(rightPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								rightPanelLayout
										.createSequentialGroup()
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																rightPanelLayout
																		.createSequentialGroup()
																		.addGap(
																				112,
																				112,
																				112)
																		.addComponent(
																				jButton5)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton6)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jButton8))
														.addGroup(
																rightPanelLayout
																		.createSequentialGroup()
																		.addGroup(
																				rightPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								rightPanelLayout
																										.createSequentialGroup()
																										.addGap(
																												37,
																												37,
																												37)
																										.addGroup(
																												rightPanelLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																rightPanelLayout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jLabel1)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																		.addComponent(
																																				txRecordNo,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				95,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addGroup(
																																rightPanelLayout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jLabel3)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																		.addComponent(
																																				txStartSal,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				143,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												rightPanelLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel2)
																														.addComponent(
																																jLabel4)))
																						.addGroup(
																								rightPanelLayout
																										.createSequentialGroup()
																										.addGap(
																												51,
																												51,
																												51)
																										.addComponent(
																												jLabel6,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												291,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGroup(
																				rightPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								rightPanelLayout
																										.createSequentialGroup()
																										.addGroup(
																												rightPanelLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																false)
																														.addGroup(
																																rightPanelLayout
																																		.createSequentialGroup()
																																		.addGap(
																																				18,
																																				18,
																																				18)
																																		.addComponent(
																																				txEndSal))
																														.addGroup(
																																rightPanelLayout
																																		.createSequentialGroup()
																																		.addGap(
																																				18,
																																				18,
																																				18)
																																		.addComponent(
																																				txId,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				107,
																																				Short.MAX_VALUE)))
																										.addGap(
																												6,
																												6,
																												6)
																										.addComponent(
																												jLabel5)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												txReason,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												98,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								rightPanelLayout
																										.createSequentialGroup()
																										.addGap(
																												88,
																												88,
																												88)
																										.addComponent(
																												result)))))
										.addGap(427, 427, 427)));
		rightPanelLayout
				.setVerticalGroup(rightPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								rightPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																35,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(result))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(jLabel2)
														.addComponent(
																txId,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txRecordNo,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(jLabel4)
														.addComponent(
																txEndSal,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel5)
														.addComponent(
																txReason,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txStartSal,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(7, 7, 7)
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton5)
														.addComponent(jButton6)
														.addComponent(jButton8))
										.addGap(31, 31, 31)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addComponent(
												leftPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(rightPanel, 0, 871,
												Short.MAX_VALUE)).addComponent(
								jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 1023,
								Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(rightPanel,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										231, Short.MAX_VALUE).addComponent(
										leftPanel,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 615,
								javax.swing.GroupLayout.PREFERRED_SIZE)));
		result.setVisible(false);
		jLabel1.setVisible(false);
		jLabel2.setVisible(false);
		jLabel3.setVisible(false);
		jLabel4.setVisible(false);
		jLabel5.setVisible(false);
		jLabel6.setVisible(false);
		jButton5.setVisible(false);
		jButton6.setVisible(false);
		jButton8.setVisible(false);
		txRecordNo.setVisible(false);
		txEndSal.setVisible(false);
		txId.setVisible(false);
		txReason.setVisible(false);
		txStartSal.setVisible(false);
		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		jLabel1.setVisible(true);
		txRecordNo.setVisible(true);
		jButton8.setVisible(true);
		jLabel6.setText("请输入你要" + jButton4.getText() + "的信息");
		jLabel6.setVisible(true);
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		jLabel1.setVisible(true);
		txRecordNo.setVisible(true);
		jButton6.setVisible(true);
		jLabel6.setText("请输入你要" + jButton2.getText() + "的信息");
		jLabel6.setVisible(true);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		jLabel2.setVisible(true);
		jLabel3.setVisible(true);
		jLabel4.setVisible(true);
		jLabel5.setVisible(true);
		txId.setVisible(true);
		txStartSal.setVisible(true);
		txEndSal.setVisible(true);
		txReason.setVisible(true);
		jButton5.setVisible(true);
		jLabel6.setText("请输入你要" + jButton1.getText() + "的信息");
		jLabel6.setVisible(true);

	}

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		staffSalService.findASalChange(jTable1, Integer.parseInt(txRecordNo
				.getText()));
		result.setVisible(true);
		txRecordNo.setText("");
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		staffSalService.delStaffSal(Integer.parseInt(txRecordNo.getText()
				.trim()));
		staffSalService.findAllStaffSal(jTable1);
		result.setVisible(true);
		txRecordNo.setText("");
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		StaffSal staffSal = new StaffSal();
		staffSal.setStaffId(Integer.parseInt(txId.getText().trim()));
		staffSal.setSalChaStart(Integer.parseInt(txStartSal.getText()));
		staffSal.setSalChaEnd(Integer.parseInt(txEndSal.getText()));
		staffSal.setSalChaReason(txReason.getText().trim());
		staffSalService.addStaffSal(staffSal);
		staffSalService.findAllStaffSal(jTable1);
		result.setVisible(true);
		txEndSal.setText("");
		txId.setText("");
		txReason.setText("");
		txStartSal.setText("");
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton8;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JPanel leftPanel;
	private javax.swing.JLabel result;
	private javax.swing.JPanel rightPanel;
	private javax.swing.JTextField txEndSal;
	private javax.swing.JTextField txId;
	private javax.swing.JTextField txReason;
	private javax.swing.JTextField txRecordNo;
	private javax.swing.JTextField txStartSal;
	// End of variables declaration//GEN-END:variables

}