/*
 * t_staff_info.java
 *
 * Created on __DATE__, __TIME__
 */

package com.itshixun.view;

import com.itshixun.model.StaffInfo;
import com.itshixun.service.StaffInfoService;
import com.itshixun.service.impl.StaffInfoServiceImpl;

/**
 * 
 * @author __USER__
 */
public class StaffInfoView extends javax.swing.JInternalFrame {
	StaffInfoService staffInfoService = new StaffInfoServiceImpl();

	/** Creates new form t_staff_info */
	public StaffInfoView() {
		initComponents();
		staffInfoService.selectAll(jTable1);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		leftPanel = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		rightPanel = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		txId = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		txPosName = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		txName = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		txDept = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		txPos = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		txSex = new javax.swing.JTextField();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jLabel7 = new javax.swing.JLabel();
		result = new javax.swing.JLabel();

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "姓名", "编号", "部门编号", "职称名称", "职位", "性别" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false,
					false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton1.setText("\u6dfb\u52a0");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton2.setText("\u5220\u9664");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton3.setText("\u66f4\u65b0");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton4.setText("\u67e5\u8be2");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(
				leftPanel);
		leftPanel.setLayout(leftPanelLayout);
		leftPanelLayout
				.setHorizontalGroup(leftPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								leftPanelLayout
										.createSequentialGroup()
										.addGap(25, 25, 25)
										.addGroup(
												leftPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jButton4)
														.addComponent(jButton3)
														.addComponent(jButton2)
														.addComponent(jButton1))
										.addContainerGap(35, Short.MAX_VALUE)));
		leftPanelLayout
				.setVerticalGroup(leftPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								leftPanelLayout
										.createSequentialGroup()
										.addGap(23, 23, 23)
										.addComponent(jButton1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton4)
										.addContainerGap(51, Short.MAX_VALUE)));

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel1.setText("\u7f16\u53f7");

		txId.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel4.setText("\u804c\u79f0\u540d\u79f0");

		txPosName.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel2.setText("\u59d3\u540d");

		txName.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel3.setText("\u90e8\u95e8\u7f16\u53f7");

		txDept.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel5.setText("\u804c\u4f4d");

		txPos.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel6.setText("\u6027\u522b");

		txSex.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jButton5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton5.setText("\u786e\u8ba4");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton6.setText("\u786e\u8ba4");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jButton7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton7.setText("\u786e\u8ba4");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		jButton8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton8.setText("\u786e\u8ba4");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});

		jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));

		result.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		result.setText("\u64cd\u4f5c\u5b8c\u6210");

		javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(
				rightPanel);
		rightPanel.setLayout(rightPanelLayout);
		rightPanelLayout
				.setHorizontalGroup(rightPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								rightPanelLayout
										.createSequentialGroup()
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																rightPanelLayout
																		.createSequentialGroup()
																		.addGap(
																				32,
																				32,
																				32)
																		.addGroup(
																				rightPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel1)
																						.addComponent(
																								jLabel4))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				rightPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								txPosName)
																						.addComponent(
																								txId,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								128,
																								Short.MAX_VALUE))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				rightPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jLabel5))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				rightPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								txName,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								93,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								txPos,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								93,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				rightPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel3)
																						.addComponent(
																								jLabel6))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				rightPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								txDept)
																						.addComponent(
																								txSex,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								98,
																								Short.MAX_VALUE)))
														.addGroup(
																rightPanelLayout
																		.createSequentialGroup()
																		.addGap(
																				130,
																				130,
																				130)
																		.addComponent(
																				jButton5)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton6)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton7)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton8))
														.addGroup(
																rightPanelLayout
																		.createSequentialGroup()
																		.addGap(
																				63,
																				63,
																				63)
																		.addComponent(
																				jLabel7,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				259,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				75,
																				75,
																				75)
																		.addComponent(
																				result)))
										.addContainerGap(120, Short.MAX_VALUE)));
		rightPanelLayout
				.setVerticalGroup(rightPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								rightPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(result)
														.addComponent(
																jLabel7,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																32,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																txId,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2)
														.addComponent(
																txName,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3)
														.addComponent(
																txDept,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																txPosName,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel5)
														.addComponent(
																txPos,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel6)
														.addComponent(
																txSex,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton5)
														.addComponent(jButton6)
														.addComponent(jButton7)
														.addComponent(jButton8))
										.addGap(74, 74, 74)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(leftPanel,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18,
						18).addComponent(rightPanel,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addComponent(jScrollPane1,
						javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, 951,
						Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING,
								false).addComponent(rightPanel, 0,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addComponent(leftPanel,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 392,
								Short.MAX_VALUE)));
		result.setVisible(false);
		jLabel1.setVisible(false);
		jLabel2.setVisible(false);
		jLabel3.setVisible(false);
		jLabel4.setVisible(false);
		jLabel5.setVisible(false);
		jLabel6.setVisible(false);
		jLabel7.setVisible(false);
		txId.setVisible(false);
		txName.setVisible(false);
		txDept.setVisible(false);
		txPosName.setVisible(false);
		txPos.setVisible(false);
		txSex.setVisible(false);
		jButton5.setVisible(false);
		jButton6.setVisible(false);
		jButton7.setVisible(false);
		jButton8.setVisible(false);
		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		staffInfoService.selectOne(jTable1, Integer.parseInt(txId.getText()));
		result.setVisible(true);
		txId.setText("");
	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		StaffInfo staffInfo = new StaffInfo();
		staffInfo.setStaffId(Integer.parseInt(txId.getText().trim()));
		staffInfo.setStaffName(txName.getText().trim());
		staffInfo.setDeptNo(Integer.parseInt(txDept.getText().trim()));
		staffInfo.setStaffPos(txPos.getText().trim());
		staffInfo.setStaffPosName(txPosName.getText().trim());
		staffInfo.setStaffSex(txSex.getText());
		staffInfoService.UpdateOne(staffInfo);
		staffInfoService.selectAll(jTable1);
		result.setVisible(true);
		txDept.setText("");
		txId.setText("");
		txName.setText("");
		txPos.setText("");
		txPosName.setText("");
		txSex.setText("");
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		staffInfoService.deleteOne(Integer.parseInt(txId.getText()));
		staffInfoService.selectAll(jTable1);
		result.setVisible(true);
		txId.setText("");
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		StaffInfo staffInfo = new StaffInfo();
		staffInfo.setStaffId(Integer.parseInt(txId.getText().trim()));
		staffInfo.setStaffName(txName.getText().trim());
		staffInfo.setDeptNo(Integer.parseInt(txDept.getText().trim()));
		staffInfo.setStaffPos(txPos.getText().trim());
		staffInfo.setStaffPosName(txPosName.getText().trim());
		staffInfo.setStaffSex(txSex.getText());
		staffInfoService.addOne(staffInfo);
		staffInfoService.selectAll(jTable1);
		result.setVisible(true);
		txDept.setText("");
		txId.setText("");
		txName.setText("");
		txPos.setText("");
		txPosName.setText("");
		txSex.setText("");
	}

	void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		jLabel1.setVisible(true);
		txId.setVisible(true);
		jButton8.setVisible(true);
		jLabel7.setText("请输入你要" + jButton4.getText() + "的信息");
		jLabel7.setVisible(true);
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		jLabel1.setVisible(true);
		jLabel2.setVisible(true);
		jLabel3.setVisible(true);
		jLabel4.setVisible(true);
		jLabel5.setVisible(true);
		jLabel6.setVisible(true);
		txId.setVisible(true);
		txName.setVisible(true);
		txDept.setVisible(true);
		txPosName.setVisible(true);
		txPos.setVisible(true);
		txSex.setVisible(true);
		jButton7.setVisible(true);
		jLabel7.setText("请输入你要" + jButton3.getText() + "的信息");
		jLabel7.setVisible(true);
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		jLabel1.setVisible(true);
		txId.setVisible(true);
		jButton6.setVisible(true);
		jLabel7.setText("请输入你要" + jButton2.getText() + "的信息");
		jLabel7.setVisible(true);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		jLabel1.setVisible(true);
		jLabel2.setVisible(true);
		jLabel3.setVisible(true);
		jLabel4.setVisible(true);
		jLabel5.setVisible(true);
		jLabel6.setVisible(true);
		txId.setVisible(true);
		txName.setVisible(true);
		txDept.setVisible(true);
		txPosName.setVisible(true);
		txPos.setVisible(true);
		txSex.setVisible(true);
		jButton5.setVisible(true);
		jLabel7.setText("请输入你要" + jButton1.getText() + "的信息");
		jLabel7.setVisible(true);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JPanel leftPanel;
	private javax.swing.JLabel result;
	private javax.swing.JPanel rightPanel;
	private javax.swing.JTextField txDept;
	private javax.swing.JTextField txId;
	private javax.swing.JTextField txName;
	private javax.swing.JTextField txPos;
	private javax.swing.JTextField txPosName;
	private javax.swing.JTextField txSex;
	// End of variables declaration//GEN-END:variables

}