/*
 * t_staff_transfer.java
 *
 * Created on __DATE__, __TIME__
 */

package com.itshixun.view;

import java.text.SimpleDateFormat;

import com.itshixun.model.StaffTransfer;
import com.itshixun.service.StaffTransferService;
import com.itshixun.service.impl.StaffTransferServiceImpl;

/**
 *
 * @author  __USER__
 */
public class StaffTransferView extends javax.swing.JInternalFrame {
	StaffTransferService staffTransferService = new StaffTransferServiceImpl();

	/** Creates new form t_staff_transfer */
	public StaffTransferView() {
		initComponents();
		staffTransferService.findStaffTransfer(jTable1);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		leftPanel = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		rightPanel = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		txRecordNo = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		txEndDept = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		txId = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		txEndPos = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		txStartDept = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		txReason = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		txStartPos = new javax.swing.JTextField();
		txDate = new javax.swing.JTextField();
		result = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "调动记录编号", "编号", "调前部门", "调前职位", "调后部门",
						"调后职位", "调动原因", "调动日期" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false,
					false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton1.setText("\u6dfb\u52a0");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton2.setText("\u5220\u9664");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton4.setText("\u67e5\u8be2");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(
				leftPanel);
		leftPanel.setLayout(leftPanelLayout);
		leftPanelLayout
				.setHorizontalGroup(leftPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								leftPanelLayout
										.createSequentialGroup()
										.addGap(31, 31, 31)
										.addGroup(
												leftPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jButton4)
														.addComponent(jButton2)
														.addComponent(jButton1))
										.addContainerGap(47, Short.MAX_VALUE)));
		leftPanelLayout.setVerticalGroup(leftPanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				leftPanelLayout.createSequentialGroup().addContainerGap()
						.addComponent(jButton1).addGap(18, 18, 18)
						.addComponent(jButton2).addGap(18, 18, 18)
						.addComponent(jButton4).addContainerGap(53,
								Short.MAX_VALUE)));

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel1.setText("\u8c03\u52a8\u8bb0\u5f55\u7f16\u53f7");

		txRecordNo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel5.setText("\u8c03\u540e\u90e8\u95e8");

		txEndDept.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel2.setText("\u7f16\u53f7");

		txId.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel6.setText("\u8c03\u540e\u804c\u4f4d");

		txEndPos.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel3.setText("\u8c03\u524d\u90e8\u95e8");

		txStartDept.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel7.setText("\u8c03\u52a8\u539f\u56e0");

		txReason.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel4.setText("\u8c03\u524d\u804c\u4f4d");

		jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel8.setText("\u8c03\u52a8\u65e5\u671f");

		txStartPos.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		txDate.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		result.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		result.setText("\u64cd\u4f5c\u5b8c\u6210");

		jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));

		jButton5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton5.setText("\u786e\u8ba4");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton6.setText("\u786e\u8ba4");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jButton8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton8.setText("\u786e\u8ba4");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(
				rightPanel);
		rightPanel.setLayout(rightPanelLayout);
		rightPanelLayout
				.setHorizontalGroup(rightPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								rightPanelLayout
										.createSequentialGroup()
										.addGap(41, 41, 41)
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																rightPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				txRecordNo,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				136,
																				Short.MAX_VALUE))
														.addGroup(
																rightPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel5)
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				rightPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								rightPanelLayout
																										.createSequentialGroup()
																										.addGap(
																												1,
																												1,
																												1)
																										.addComponent(
																												jButton5)
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												jButton6)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED))
																						.addComponent(
																								txEndDept,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								181,
																								Short.MAX_VALUE))))
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																rightPanelLayout
																		.createSequentialGroup()
																		.addGap(
																				9,
																				9,
																				9)
																		.addGroup(
																				rightPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel6)
																						.addComponent(
																								jLabel2))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				rightPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								txId)
																						.addComponent(
																								txEndPos,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								139,
																								Short.MAX_VALUE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				rightPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel7)
																						.addComponent(
																								jLabel3))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				rightPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								txReason)
																						.addComponent(
																								txStartDept,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								136,
																								Short.MAX_VALUE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				rightPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								rightPanelLayout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel4)
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												txStartPos,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												133,
																												Short.MAX_VALUE))
																						.addGroup(
																								rightPanelLayout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel8)
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												txDate,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												133,
																												Short.MAX_VALUE))))
														.addGroup(
																rightPanelLayout
																		.createSequentialGroup()
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton8)))
										.addGap(217, 217, 217))
						.addGroup(
								rightPanelLayout
										.createSequentialGroup()
										.addGap(76, 76, 76)
										.addComponent(
												jLabel9,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												313,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(46, 46, 46)
										.addComponent(result).addContainerGap(
												793, Short.MAX_VALUE)));
		rightPanelLayout
				.setVerticalGroup(rightPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								rightPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jLabel9,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																32,
																Short.MAX_VALUE)
														.addComponent(
																result,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(jLabel2)
														.addComponent(jLabel3)
														.addComponent(jLabel4)
														.addComponent(
																txRecordNo,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txStartDept,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txId,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txStartPos,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(jLabel6)
														.addComponent(jLabel7)
														.addComponent(jLabel8)
														.addComponent(
																txDate,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txEndDept,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txReason,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txEndPos,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton6)
														.addComponent(jButton5)
														.addComponent(jButton8))
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												leftPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												rightPanel,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)).addComponent(
								jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 1492,
								Short.MAX_VALUE));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				leftPanel,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addGap(
																				1,
																				1,
																				1))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				rightPanel,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												620,
												javax.swing.GroupLayout.PREFERRED_SIZE)));
		result.setVisible(false);
		jLabel1.setVisible(false);
		jLabel2.setVisible(false);
		jLabel3.setVisible(false);
		jLabel4.setVisible(false);
		jLabel5.setVisible(false);
		jLabel6.setVisible(false);
		jLabel7.setVisible(false);
		jLabel8.setVisible(false);
		txId.setVisible(false);
		txStartDept.setVisible(false);
		txStartPos.setVisible(false);
		txRecordNo.setVisible(false);
		txEndDept.setVisible(false);
		txEndPos.setVisible(false);
		txReason.setVisible(false);
		txDate.setVisible(false);
		jButton5.setVisible(false);
		jButton6.setVisible(false);
		jButton8.setVisible(false);
		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		jLabel1.setVisible(true);
		txRecordNo.setVisible(true);
		jButton8.setVisible(true);
		jLabel9.setText("请输入你要" + jButton4.getText() + "的信息");
		jLabel9.setVisible(true);
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		jLabel1.setVisible(true);
		txRecordNo.setVisible(true);
		jButton6.setVisible(true);
		jLabel9.setText("请输入你要" + jButton2.getText() + "的信息");
		jLabel9.setVisible(true);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		jLabel2.setVisible(true);
		jLabel3.setVisible(true);
		jLabel4.setVisible(true);
		jLabel5.setVisible(true);
		jLabel6.setVisible(true);
		jLabel7.setVisible(true);
		jLabel8.setVisible(true);
		txId.setVisible(true);
		txStartDept.setVisible(true);
		txStartPos.setVisible(true);
		txEndDept.setVisible(true);
		txEndPos.setVisible(true);
		txReason.setVisible(true);
		txDate.setVisible(true);
		jButton5.setVisible(true);
		jLabel9.setText("请输入你要" + jButton1.getText() + "的信息");
		jLabel9.setVisible(true);
	}

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		staffTransferService.findAStaffTransfer(Integer.parseInt(txRecordNo
				.getText()), jTable1);
		result.setVisible(true);
		txRecordNo.setText("");
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		staffTransferService.delStaffTransfer(Integer.parseInt(txRecordNo
				.getText().trim()));
		staffTransferService.findStaffTransfer(jTable1);
		result.setVisible(true);
		txRecordNo.setText("");
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
		try {
			String start = txDate.getText().trim();
			java.util.Date uDate = new java.util.Date();
			uDate = simpleDateFormat.parse(start);
			java.sql.Date date = new java.sql.Date(uDate.getTime());

			StaffTransfer staffTransfer = new StaffTransfer();
			staffTransfer.setStaffId(Integer.parseInt(txId.getText().trim()));
			staffTransfer.setTransferstartDept(txStartDept.getText().trim());
			staffTransfer.setTransferstartPos(txStartPos.getText().trim());
			staffTransfer.setTransferendDept(txEndDept.getText());
			staffTransfer.setTransferendPos(txEndPos.getText());
			staffTransfer.setTransferReason(txReason.getText());
			staffTransfer.setTransferDate(date);
			staffTransferService.addStaffTransfer(staffTransfer);
			staffTransferService.findStaffTransfer(jTable1);
			result.setVisible(true);
		} catch (Exception e) {
			e.printStackTrace();
		}
		txDate.setText("");
		txEndDept.setText("");
		txEndPos.setText("");
		txId.setText("");
		txReason.setText("");
		txStartDept.setText("");
		txStartPos.setText("");
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton8;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JPanel leftPanel;
	private javax.swing.JLabel result;
	private javax.swing.JPanel rightPanel;
	private javax.swing.JTextField txDate;
	private javax.swing.JTextField txEndDept;
	private javax.swing.JTextField txEndPos;
	private javax.swing.JTextField txId;
	private javax.swing.JTextField txReason;
	private javax.swing.JTextField txRecordNo;
	private javax.swing.JTextField txStartDept;
	private javax.swing.JTextField txStartPos;
	// End of variables declaration//GEN-END:variables

}