/*
 * UserPaneView.java
 *
 * Created on __DATE__, __TIME__
 */

package com.itshixun.view;

import com.itshixun.model.User;
import com.itshixun.service.UserService;
import com.itshixun.service.impl.UserServiceImpl;

/**
 * 
 * @author __USER__
 */
public class TUser extends javax.swing.JInternalFrame {
	UserService userService = new UserServiceImpl();

	/** Creates new form UserPaneView */
	public TUser() {

		initComponents();
		userService.findAllUser(jTable1);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		leftPanel = new javax.swing.JPanel();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();
		rightPanel = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		txName = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		txPwd = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		txType = new javax.swing.JTextField();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		result = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		txNo = new javax.swing.JTextField();

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "编号", "用户名", "密码", "角色 " }) {
			boolean[] canEdit = new boolean[] { false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jButton3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton3.setText("\u66f4\u65b0");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton4.setText("\u67e5\u8be2");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton2.setText("\u5220\u9664");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton1.setText("\u6dfb\u52a0");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(
				leftPanel);
		leftPanel.setLayout(leftPanelLayout);
		leftPanelLayout
				.setHorizontalGroup(leftPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								leftPanelLayout
										.createSequentialGroup()
										.addGap(29, 29, 29)
										.addGroup(
												leftPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jButton3)
														.addComponent(jButton4)
														.addComponent(jButton2)
														.addComponent(jButton1))
										.addContainerGap(28, Short.MAX_VALUE)));
		leftPanelLayout
				.setVerticalGroup(leftPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								leftPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jButton1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton4)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel1.setText("\u7528\u6237\u540d");

		txName.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel2.setText("\u5bc6\u7801");

		txPwd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel3.setText("\u6743\u9650");

		txType.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		jButton5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton5.setText("\u786e\u8ba4");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton6.setText("\u786e\u8ba4");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jButton7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton7.setText("\u786e\u8ba4");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		jButton8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton8.setText("\u786e\u8ba4");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));

		result.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		result.setText("\u64cd\u4f5c\u5b8c\u6210");

		jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel5.setText("\u8981\u4fee\u6539\u7684\u7f16\u53f7");

		txNo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));

		javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(
				rightPanel);
		rightPanel.setLayout(rightPanelLayout);
		rightPanelLayout
				.setHorizontalGroup(rightPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								rightPanelLayout
										.createSequentialGroup()
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																rightPanelLayout
																		.createSequentialGroup()
																		.addGap(
																				54,
																				54,
																				54)
																		.addComponent(
																				jButton5)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton6)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jButton7)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton8))
														.addGroup(
																rightPanelLayout
																		.createSequentialGroup()
																		.addGroup(
																				rightPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								rightPanelLayout
																										.createSequentialGroup()
																										.addGap(
																												36,
																												36,
																												36)
																										.addGroup(
																												rightPanelLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel5)
																														.addComponent(
																																jLabel1))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												rightPanelLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																false)
																														.addComponent(
																																txNo)
																														.addComponent(
																																txName,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																107,
																																Short.MAX_VALUE))
																										.addGap(
																												29,
																												29,
																												29)
																										.addGroup(
																												rightPanelLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel2)
																														.addComponent(
																																jLabel3)))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								rightPanelLayout
																										.createSequentialGroup()
																										.addGap(
																												56,
																												56,
																												56)
																										.addComponent(
																												jLabel4,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												295,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				rightPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								txPwd,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								189,
																								Short.MAX_VALUE)
																						.addGroup(
																								rightPanelLayout
																										.createSequentialGroup()
																										.addGap(
																												65,
																												65,
																												65)
																										.addComponent(
																												result))
																						.addComponent(
																								txType))))
										.addContainerGap(230, Short.MAX_VALUE)));
		rightPanelLayout
				.setVerticalGroup(rightPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								rightPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																29,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(result))
										.addGap(18, 18, 18)
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(
																txNo,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3)
														.addComponent(
																txType,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																txName,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2)
														.addComponent(
																txPwd,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton5)
														.addComponent(jButton6)
														.addComponent(jButton7)
														.addComponent(jButton8))
										.addGap(1, 1, 1)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(leftPanel,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE).addGap(12, 12,
						12).addComponent(rightPanel,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addComponent(jScrollPane1,
						javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, 945,
						Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(rightPanel,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										223, Short.MAX_VALUE).addComponent(
										leftPanel,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 619,
								javax.swing.GroupLayout.PREFERRED_SIZE)));
		result.setVisible(false);
		jLabel1.setVisible(false);
		jLabel2.setVisible(false);
		jLabel3.setVisible(false);
		jLabel4.setVisible(false);
		jLabel5.setVisible(false);
		txName.setVisible(false);
		txNo.setVisible(false);
		txPwd.setVisible(false);
		txType.setVisible(false);
		jButton5.setVisible(false);
		jButton6.setVisible(false);
		jButton7.setVisible(false);
		jButton8.setVisible(false);
		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		userService.findAUser(txName.getText().trim(), jTable1);
		result.setVisible(true);
		txNo.setText("");
	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		User user = new User();
		user.setUserNo(Integer.parseInt(txNo.getText().trim()));
		user.setUserName(txName.getText().trim());
		user.setUserPwd(txPwd.getText().trim());
		user.setTypeNo(Integer.parseInt(txType.getText().trim()));
		userService.UpdateUser(user);
		userService.findAllUser(jTable1);
		result.setVisible(true);
		txName.setText("");
		txNo.setText("");
		txPwd.setText("");
		txType.setText("");
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		userService.DelUser(txName.getText().trim());
		userService.findAllUser(jTable1);
		result.setVisible(true);
		txNo.setText("");
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		User user = new User();
		user.setUserName(txName.getText().trim());
		user.setUserPwd(txPwd.getText().trim());
		user.setTypeNo(Integer.parseInt(txType.getText().trim()));
		userService.AddUser(user);
		userService.findAllUser(jTable1);
		result.setVisible(true);
		txName.setText("");
		txPwd.setText("");
		txType.setText("");
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		jLabel1.setVisible(true);
		txName.setVisible(true);
		jButton8.setVisible(true);
		jLabel4.setText("请输入你要" + jButton4.getText() + "的信息");
		jLabel4.setVisible(true);
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		jLabel1.setVisible(true);
		jLabel2.setVisible(true);
		jLabel3.setVisible(true);
		txName.setVisible(true);
		txPwd.setVisible(true);
		txType.setVisible(true);
		jButton7.setVisible(true);
		jLabel4.setText("请输入你要" + jButton3.getText() + "的信息");
		jLabel4.setVisible(true);
		jLabel5.setVisible(true);
		txNo.setVisible(true);
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		jLabel1.setVisible(true);
		txName.setVisible(true);
		jButton6.setVisible(true);
		jLabel4.setText("请输入你要" + jButton2.getText() + "的信息");
		jLabel4.setVisible(true);

	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < rightPanel.getComponentCount(); i++) {
			rightPanel.getComponent(i).setVisible(false);
		}
		jLabel1.setVisible(true);
		jLabel2.setVisible(true);
		jLabel3.setVisible(true);
		txName.setVisible(true);
		txPwd.setVisible(true);
		txType.setVisible(true);
		jButton5.setVisible(true);
		jLabel4.setText("请输入你要" + jButton1.getText() + "的信息");
		jLabel4.setVisible(true);

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	public javax.swing.JButton jButton1;
	public javax.swing.JButton jButton2;
	public javax.swing.JButton jButton3;
	public javax.swing.JButton jButton4;
	public javax.swing.JButton jButton5;
	public javax.swing.JButton jButton6;
	public javax.swing.JButton jButton7;
	public javax.swing.JButton jButton8;
	public javax.swing.JLabel jLabel1;
	public javax.swing.JLabel jLabel2;
	public javax.swing.JLabel jLabel3;
	public javax.swing.JLabel jLabel4;
	public javax.swing.JLabel jLabel5;
	public javax.swing.JScrollPane jScrollPane1;
	public javax.swing.JTable jTable1;
	public javax.swing.JPanel leftPanel;
	public javax.swing.JLabel result;
	public javax.swing.JPanel rightPanel;
	public javax.swing.JTextField txName;
	public javax.swing.JTextField txNo;
	public javax.swing.JTextField txPwd;
	public javax.swing.JTextField txType;
	// End of variables declaration//GEN-END:variables

}