/*
 * UserType.java
 *
 * Created on __DATE__, __TIME__
 */

package com.itshixun.view;

import com.itshixun.service.UserTypeService;
import com.itshixun.service.impl.UserTypeServiceImpl;
import com.itshixun.model.*;

/**
 * 
 * @author __USER__
 */
public class UserTypeView extends javax.swing.JInternalFrame {
	UserTypeService userTypeService = new UserTypeServiceImpl();

	/** Creates new form UserType */
	public UserTypeView() {
		initComponents();
		userTypeService.showAllUserType(jTable1);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		leftPanel = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		rightPanel = new javax.swing.JPanel();
		jButton5 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		txTypeName = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		txTypeNo = new javax.swing.JTextField();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		result = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "权限", "编号" }) {
			boolean[] canEdit = new boolean[] { false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton1.setText("\u6dfb\u52a0");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton2.setText("\u5220\u9664");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton3.setText("\u66f4\u65b0");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton4.setText("\u67e5\u8be2");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(
				leftPanel);
		leftPanel.setLayout(leftPanelLayout);
		leftPanelLayout
				.setHorizontalGroup(leftPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								leftPanelLayout
										.createSequentialGroup()
										.addGap(34, 34, 34)
										.addGroup(
												leftPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jButton4)
														.addComponent(jButton3)
														.addComponent(jButton2)
														.addComponent(jButton1))
										.addContainerGap(48, Short.MAX_VALUE)));
		leftPanelLayout
				.setVerticalGroup(leftPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								leftPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jButton1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jButton2)
										.addGap(16, 16, 16)
										.addComponent(jButton3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jButton4)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jButton5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton5.setText("\u786e\u8ba4");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel1.setText("\u6743\u9650");

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel2.setText("\u7f16\u53f7");

		jButton6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton6.setText("\u786e\u8ba4");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jButton7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton7.setText("\u786e\u8ba4");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		jButton8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton8.setText("\u786e\u8ba4");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});

		result.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		result.setText("\u64cd\u4f5c\u5b8c\u6210");

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));

		javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(
				rightPanel);
		rightPanel.setLayout(rightPanelLayout);
		rightPanelLayout
				.setHorizontalGroup(rightPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								rightPanelLayout
										.createSequentialGroup()
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																rightPanelLayout
																		.createSequentialGroup()
																		.addGap(
																				55,
																				55,
																				55)
																		.addGroup(
																				rightPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								rightPanelLayout
																										.createSequentialGroup()
																										.addGap(
																												10,
																												10,
																												10)
																										.addComponent(
																												jButton5)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												jButton6)
																										.addGap(
																												15,
																												15,
																												15)
																										.addComponent(
																												jButton7)
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												jButton8))
																						.addGroup(
																								rightPanelLayout
																										.createSequentialGroup()
																										.addGroup(
																												rightPanelLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																														.addComponent(
																																jLabel1)
																														.addComponent(
																																jLabel2))
																										.addGap(
																												15,
																												15,
																												15)
																										.addGroup(
																												rightPanelLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																false)
																														.addComponent(
																																txTypeNo)
																														.addComponent(
																																txTypeName,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																133,
																																Short.MAX_VALUE)))))
														.addGroup(
																rightPanelLayout
																		.createSequentialGroup()
																		.addGap(
																				69,
																				69,
																				69)
																		.addComponent(
																				jLabel3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				250,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				result)))
										.addGap(198, 198, 198)));
		rightPanelLayout
				.setVerticalGroup(rightPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								rightPanelLayout
										.createSequentialGroup()
										.addContainerGap(31, Short.MAX_VALUE)
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jLabel3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																34,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(result))
										.addGap(9, 9, 9)
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																txTypeName,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(12, 12, 12)
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																txTypeNo,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												rightPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton5)
														.addComponent(jButton6)
														.addComponent(jButton7)
														.addComponent(jButton8))
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												leftPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												rightPanel,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												635, Short.MAX_VALUE))
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.DEFAULT_SIZE, 807,
								Short.MAX_VALUE));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																leftPanel,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																228,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																rightPanel,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												592,
												javax.swing.GroupLayout.PREFERRED_SIZE)));
		result.setVisible(false);
		txTypeName.setEnabled(false);
		txTypeNo.setEnabled(false);
		jButton5.setVisible(false);
		jButton6.setVisible(false);
		jButton7.setVisible(false);
		jButton8.setVisible(false);
		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		userTypeService.showAUserType(Integer.parseInt(txTypeNo.getText()),
				jTable1);
		result.setVisible(true);
		txTypeName.setEnabled(false);
		txTypeNo.setEnabled(false);
		jButton8.setVisible(false);
		txTypeNo.setText("");
	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		UserType userType = new UserType();
		userType.setTypeName(txTypeName.getText().trim());
		userType.setTypeNo(Integer.parseInt(txTypeNo.getText().trim()));
		userTypeService.UpdateUserType(userType);
		userTypeService.showAllUserType(jTable1);
		result.setVisible(true);
		txTypeName.setEnabled(false);
		txTypeNo.setEnabled(false);
		jButton7.setVisible(false);
		txTypeName.setText("");
		txTypeNo.setText("");
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		userTypeService
				.DelUserType(Integer.parseInt(txTypeNo.getText().trim()));
		userTypeService.showAllUserType(jTable1);
		result.setVisible(true);
		txTypeName.setEnabled(false);
		txTypeNo.setEnabled(false);
		jButton6.setVisible(false);
		txTypeNo.setText("");
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		UserType userType = new UserType();
		userType.setTypeName(txTypeName.getText().trim());
		userType.setTypeNo(Integer.parseInt(txTypeNo.getText()));
		userTypeService.AddUserType(userType);
		userTypeService.showAllUserType(jTable1);
		result.setVisible(true);
		txTypeName.setEnabled(false);
		txTypeNo.setEnabled(false);
		jButton5.setVisible(false);
		txTypeName.setText("");
		txTypeNo.setText("");
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		txTypeName.setEnabled(true);
		txTypeNo.setEnabled(true);
		jButton7.setVisible(true);
		jButton5.setVisible(false);
		jButton6.setVisible(false);
		jButton8.setVisible(false);
		jLabel3.setText("请输入你要" + jButton3.getText() + "的信息");
		jLabel3.setVisible(true);
	}

	void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		txTypeName.setEnabled(false);
		txTypeNo.setEnabled(true);
		jButton8.setVisible(true);
		jButton5.setVisible(false);
		jButton6.setVisible(false);
		jButton7.setVisible(false);
		jLabel3.setText("请输入你要" + jButton4.getText() + "的信息");
		jLabel3.setVisible(true);
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		txTypeName.setEnabled(false);
		txTypeNo.setEnabled(true);
		jButton6.setVisible(true);
		jButton5.setVisible(false);
		jButton7.setVisible(false);
		jButton8.setVisible(false);
		jLabel3.setText("请输入你要" + jButton2.getText() + "的信息");
		jLabel3.setVisible(true);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		txTypeName.setEnabled(true);
		txTypeNo.setEnabled(true);
		jButton5.setVisible(true);
		jButton6.setVisible(false);
		jButton7.setVisible(false);
		jButton8.setVisible(false);
		jLabel3.setText("请输入你要" + jButton1.getText() + "的信息");
		jLabel3.setVisible(true);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JPanel leftPanel;
	private javax.swing.JLabel result;
	private javax.swing.JPanel rightPanel;
	private javax.swing.JTextField txTypeName;
	private javax.swing.JTextField txTypeNo;
	// End of variables declaration//GEN-END:variables

}